close all; clear; clc;
Fs = 256;
ts = 1/Fs;
t = 0:ts:1;
fa = 5;
fb = 10;
fc = 20;
fcut=11;
a_t = sin(2 * pi *fa*t);
b_t = sin(2 * pi* fb*t);
c_t = sin(2 * pi * fc*t);
y = a_t + b_t + c_t;
subplot(4,1,1);
plot(t, y);
f = fft(y);
title("fa & fb & fc");
subplot(4,1,2);
plot (t,f);
y1 = a_t + b_t;
title("fft");
subplot(4,1,4);
plot(t,y1);
title("fa & fb");
[b,a] = butter(2,fcut/(Fs/2));
f_t = filter(b,a,y);
subplot(4,1,3);
plot(t,f_t);
title("Filtered");